-- * CREACION DE BASE DE DATOS
CREATE DATABASE FERRETERIAS
GO
-- * USAR BASE DE DATOS
USE FERRETERIAS
GO

-- * CREAR TABLAS
CREATE TABLE FERRETERIAS (
    FERRID INT NOT NULL,
    FERRNOMBRE NVARCHAR(50) NOT NULL,
    FERRDOMICILIO NVARCHAR(50) NOT NULL,
    FERRTELEFONO NCHAR(10) NULL)
GO
CREATE TABLE ZONAS (
    ZONAID INT NOT NULL,
    ZONANOMBRE NVARCHAR(50) NOT NULL)
GO
CREATE TABLE EMPLEADOS (
    EMPID INT NOT NULL,
    EMPNOMRE NVARCHAR(50) NOT NULL,
    EMPAPEPAT NVARCHAR(50) NOT NULL,
    EMPAPEMAT NVARCHAR(50) NULL,
    EMPDOMICILIO NVARCHAR(50) NOT NULL,
    EMPTELEFONO NCHAR(10) NULL,
    EMPCELULAR NCHAR(10) NULL,
    EMPRFC NCHAR(13) NULL,
    EMPCURP NCHAR(18) NULL,
    EMPFECHAINGRESO DATE NOT NULL,
    EMPFECHANACIMIENTO DATE NOT NULL,
    ZONAID INT NOT NULL,
    JEFE INT NULL)
GO
CREATE TABLE MUNICIPIOS (
    MUNID INT NOT NULL,
    MUNNOMBRE NVARCHAR(50) NOT NULL)
GO
CREATE TABLE COLONIAS (
    COLID INT NOT NULL,
    COLNOMBRE NVARCHAR(50) NOT NULL,
    COLCP NCHAR(5) NULL,
    MUNID INT NOT NULL)
GO
CREATE TABLE CLIENTES (
    CTEID INT NOT NULL,
    CTENOMBRE NVARCHAR(50) NOT NULL,
    CTEAPEPAT NVARCHAR(50) NOT NULL,
    CTEAPEMAT NVARCHAR(50) NULL,
    CTEDOMICILIOS NVARCHAR(50) NOT NULL,
    CTETELEFONO NCHAR(10) NULL,
    CTECELULAR NCHAR(10) NULL,
    CTERFC NCHAR(13) NULL,
    CTECURP NCHAR(18) NULL,
    CTEFECHANACIMIENTO DATE NOT NULL,
    CTESEXO NCHAR(1) NOT NULL,
    COLID INT NOT NULL)
GO
CREATE TABLE VENTAS (
    FOLIO INT NOT NULL,
    FECHA DATETIME NOT NULL,
    FERRID INT NOT NULL,
    CTEID INT NOT NULL,
    EMPID INT NOT NULL)

CREATE TABLE FAMILIAS (
    FAMID INT NOT NULL,
    FAMNOMBRE NVARCHAR(50) NOT NULL)
GO
CREATE TABLE ARTICULOS (
    ARTID INT NOT NULL,
    ARTNOMBRE NVARCHAR(50) NOT NULL,
    ARTDESCRIPCION NVARCHAR(200) NOT NULL,
    ARTPRECIO NUMERIC(10,2) NOT NULL,
    FAMID INT NOT NULL)
GO 
CREATE TABLE DETALLE (
    FOLIO INT NOT NULL,
    ARTID INT NOT NULL,
    CANTIDAD NUMERIC(7,2) NOT NULL,
    PRECIO NUMERIC(10,2) NOT NULL)
GO

-- * CLAVES PRIMARIAS
ALTER TABLE CLIENTES ADD CONSTRAINT pkClientes PRIMARY KEY (CTEID)

ALTER TABLE DETALLE ADD CONSTRAINT pkDetalle PRIMARY KEY (FOLIO, ARTID)
-- * CLAVES FORANEAS
ALTER TABLE CLIENTES ADD CONSTRAINT fkClientesColonias FOREIGN KEY (COLID) REFERENCES COLONIAS(COLID)

ALTER TABLE VENTAS ADD 
CONSTRAINT fkVentasFerreterias FOREIGN KEY (FERRID) REFERENCES FERRETERIAS(FERRID),
CONSTRAINT fkVentasClientes FOREIGN KEY (CTEID) REFERENCES CLIENTES (CTEID),
CONSTRAINT fkVentasEmpleados FOREIGN KEY (EMPID) REFERENCES EMPLEADOS (EMPID)
-- * UNIQUE
ALTER TABLE CLIENTES ADD CONSTRAINT ucClientesCurp UNIQUE (CTECURP)
-- * DEFAULTS
ALTER TABLE CLIENTES ADD CONSTRAINT dfClientesCelular DEFAULT '0000000000'
-- * ASIGNACION DE VALORES DE COMPROBACION (CHECK)
ALTER TABLE CLIENTES ADD CONSTRAINT chkClientesNacimiento CHECK (CTEFECHANACIMIENTO < GETDATE())
ALTER TABLE ARTICULOS ADD CONSTRAINT chkArticulosPrecio CHECK (ARTPRECIO >= 0)

-- * INSERTS 
INSERT INTO MUNICIPIOS (MUNID, MUNNOMBRE) VALUES (1, 'Sanalona')
