-- *CREACIÓN DE LA BASE DE DATOS
CREATE DATABASE CONGRESOS
GO

-- *USAR LA BASE DE DATOS
USE CONGRESOS
GO

-- *CREACIÓN DE TABLAS
CREATE TABLE CONGRESOS(
    CONID INT NOT NULL,
    CONNOMBRE NVARCHAR(50) NOT NULL,
    CONDESCRIPCION NVARCHAR(200) NULL,
    CONFECHAINI DATE NOT NULL,
    CONFECHAFIN DATE NOT NULL,
    CONLUGAR NVARCHAR(50) NOT NULL)
GO
CREATE TABLE EXPOSITORES(
    EXPID INT NOT NULL,
    EXPNOMBRE NVARCHAR(50) NOT NULL,
    EXPAPEPAT NVARCHAR(50) NOT NULL,
    EXPAPEMAT NVARCHAR(50) NULL,
    EXPCORREO NVARCHAR(50) NULL,
    EXPCELULAR NCHAR(10) NULL)
GO
CREATE TABLE EVENTOS(
    EVEID INT NOT NULL,
    EVENOMBRE NVARCHAR(50) NOT NULL,
    EVEDESCRIPCION NVARCHAR(200) NULL,
    EVEFECHA DATE NOT NULL,
    EVELUGAR NVARCHAR(50) NOT NULL,
    EVECOSTO NUMERIC(10,2) NOT NULL,
    EXPID INT NOT NULL)
GO
CREATE TABLE MUNICIPIOS(
    MUNID INT NOT NULL,
    MUNNOMBRE NVARCHAR(50) NOT NULL)
GO
CREATE TABLE ESCUELAS (
    ESCID INT NOT NULL,
    ESCNOMBRE NVARCHAR(50) NOT NULL,
    ESCDOMICILIO NVARCHAR(50) NOT NULL,
    MUNID INT NOT NULL)
GO
CREATE TABLE ESTUDIANTES(
    ESTID INT NOT NULL,
    ESTNOMBRE NVARCHAR(50) NOT NULL,
    ESTAPEPAT NVARCHAR(50) NOT NULL,
    ESTAPEMAT NVARCHAR(50) NULL,
    ESTDOMICILIO NVARCHAR(50) NOT NULL,
    ESTCORREO NVARCHAR(50) NULL,
    ESTCELULAR NCHAR(10) NULL,
    ESCID INT NOT NULL)
GO
CREATE TABLE REGISTRO (
    FOLIO INT NOT NULL,
    FECHA DATE NOT NULL,
    CONID INT NOT NULL,
    ESTID INT NOT NULL)
GO
CREATE TABLE REGISTROXEVENTOS(
    FOLIO INT NOT NULL,
    EVEID INT NOT NULL)
GO

-- *CREACION DE LLAVES PRIMARIAS
ALTER TABLE CONGRESOS ADD CONSTRAINT pkCongresos PRIMARY KEY (CONID)
GO
ALTER TABLE REGISTRO ADD CONSTRAINT pkRegistro PRIMARY KEY (FOLIO)
GO
ALTER TABLE EXPOSITORES ADD CONSTRAINT pkExpositores PRIMARY KEY (EXPID)
GO
ALTER TABLE EVENTOS ADD CONSTRAINT pkEventos PRIMARY KEY (EVEID)
GO
ALTER TABLE ESTUDIANTES ADD CONSTRAINT pkEstudiantes PRIMARY KEY (ESTID)
GO
ALTER TABLE ESCUELAS ADD CONSTRAINT pkEscuelas PRIMARY KEY (ESCID)
GO 
ALTER TABLE MUNICIPIOS ADD CONSTRAINT pkMunicipios PRIMARY KEY (MUNID)
GO
ALTER TABLE REGISTROXEVENTOS ADD CONSTRAINT pkUnionRegistro PRIMARY KEY (FOLIO)
GO
ALTER TABLE REGISTROXEVENTOS ADD CONSTRAINT pkUnionEventos PRIMARY KEY (EVEID)
GO

-- *CREACION DE LLAVES FORANEAS
ALTER TABLE REGISTRO ADD
CONSTRAINT fkRegistroCongresos FOREIGN KEY (CONID) REFERENCES CONGRESOS(CONID)
GO
ALTER TABLE REGISTRO ADD
CONSTRAINT fkRegistroEstudiantes FOREIGN KEY (ESTID) REFERENCES ESTUDIANTES(ESTID)
GO
ALTER TABLE ESTUDIANTES ADD
CONSTRAINT fkEstudiantesEscuelas FOREIGN KEY (ESCID) REFERENCES ESCUELAS (ESCID)
GO
ALTER TABLE ESCUELAS ADD
CONSTRAINT fkEscuelasMunicipios FOREIGN KEY (MUNID) REFERENCES MUNICIPIOS (MUNID)
GO
ALTER TABLE EVENTOS ADD
CONSTRAINT fkEventosExpositores FOREIGN KEY (EXPID) REFERENCES EXPOSITORES (EXPID)
GO
ALTER TABLE REGISTROXEVENTOS ADD
CONSTRAINT fkUnionRegistro FOREIGN KEY (FOLIO) REFERENCES REGISTRO (FOLIO)
GO
ALTER TABLE REGISTROXEVENTOS ADD
CONSTRAINT fkUnionEventos FOREIGN KEY (EVEID) REFERENCES EVENTOS (EVEID)

-- *CREACION DE LLAVES UNICAS

-- *ASIGNACION DE VALORES POR DEFAULT

-- *ASIGNACION DE VALORES DE COMPROBACION

-- *5 INSERCIONES POR CADA TABLA