CREATE DATABASE VENTAS
GO
USE VENTAS
GO 
CREATE TABLE PROVEEDORES(
PROVID INT NOT NULL,
PROVNOMBRE VARCHAR(20) NOT NULL,
PROVDIRECCION VARCHAR(20) NULL,
PROVTELEFONO VARCHAR(20) NULL)
GO 
-- CASO GENERAL
INSERT INTO PROVEEDORES(PROVID, PROVNOMBRE, PROVDIRECCION, PROVTELEFONO)
		VALUES		   (  1  ,'JUAN PEREZ','OBREGON 33', '01-667,1234,233')
GO
-- CAMBIANDO EL ORDEN DE LOS CAMPOS
INSERT PROVEEDORES (PROVDIRECCION, PROVTELEFONO, PROVNOMBRE, PROVID)
		VALUES ('OBREGON 34', '01-667-1234-233', 'ANA LOPEZ', 2)
GO
-- SI SE PASAN TODOS LOS VALORES, SE PUEDE OMITIR LA LISTA DE COLUMNAS SOLO QUE
-- TIENEN QUE ESTAR LOS VALORES A INSERTARSE EN EL ORDEN EN QUE FUERON CREADOS
INSERT PROVEEDORES VALUES (3, 'JESUS GUZMAN', 'ZAPATA 34', '01-667-1234-223')
GO
--SI SE PUEDEN OMITIR LAS COLUMNAS QUE PERMITEN VALORES NULOS, PERO ES NECESARIO
--ESPECIFICAR LOS NOMBRES DE LOS CAMPOS QUE SI TENDRAN VALORES
INSERT PROVEEDORES (PROVID, PROVNOMBRE)
			VALUES(4, 'PEDRO CASTRO')
GO

-- SI SE DESEA INSERTAR UN VALOR NULO EN UN CAMPO QUE LO ACEPTE, SE TIENE QUE
-- ESPECIFICAR EN EL LISTADO DE VALORES
<<<<<<< HEAD
INSERT PROVEEDORES (PROVID, PROVNOMBRE, PROVDIRECCION)
			VALUES(5, 'EVA CASTRO', null)
=======
INSERT PROVEEDORES(PROVID, PROVNOMBRE, PROVDIRECCION)
VALUES (5, 'EVA CASTRO', NULL)
>>>>>>> 779ab5f (CONGRESO.SQL CREATED)

SELECT * FROM PROVEEDORES

-- INSERTAR DATOS CON UNA CONSULTA
INSERT PROVEEDORES
SELECT PROVID + 10, PROVNOMBRE, PROVDIRECCION, PROVTELEFONO FROM PROVEEDORES

SELECT * FROM PROVEEDORES

-- CREACION E INSERCION DE DATOS CON UNA SOLA INSTRUCCION
SELECT *
INTO PROVEEDORES3
FROM PROVEEDORES

SELECT * FROM PROVEEDORES3

-- CREACION DE UN PROC ALMACENADO
CREATE PROCEDURE SP_LLENA
AS
BEGIN
    SELECT PROVID, PROVNOMBRE
    FROM PROVEEDORES;
END;
GO

-- EJECUCION DE UN PROC ALMACENADO
EXEC SP_LLENA

-- UTILIZACION CON UN INSERT
INSERT PROVEEDORES3 (PROVID, PROVNOMBRE)
EXEC SP_LLENA

SELECT * FROM PROVEEDORES

SELECT * FROM PROVEEDORES3

<<<<<<< HEAD
-- INSERTAR CINCO REGISTROS A CADA TABLA
GO
INSERT PROVEEDORES VALUES (6, 'Victoria Ontiveros', 'Villa del real #2742', '52-667-795-5011')
GO
INSERT PROVEEDORES VALUES (7, 'Oliver Estrada', 'Villas del rio #3110', '52-662-208-3822')
GO
INSERT PROVEEDORES VALUES (8, 'Cristofer Aguilar', null, '52-667-859-6359')
GO
INSERT PROVEEDORES(PROVNOMBRE, PROVTELEFONO, PROVID) VALUES ('Enrique Archuleta', '52-668-456-1222', 9)
GO
INSERT PROVEEDORES(PROVID, PROVNOMBRE, PROVTELEFONO, PROVDIRECCION) VALUES (10, 'Yovanni Inzunza', '52-667-278-7456', 'Jardin #310')

SELECT * FROM PROVEEDORES
=======
-- 
>>>>>>> 779ab5f (CONGRESO.SQL CREATED)
