---------------------------
--- CONSULTAS NORTHWIND ---
---------------------------
-- SENTENCIA SELECT SIMPLE --

-- HAY TRES COMPONENTES BASICOS EN LAS CONSULTAS:
-- SELECT COLUMN_LIST
-- FROM TABLE_LIST
-- [WHERE SEARCH_CRITEARIA]
use Northwind

-- EJEMPLO MUESTRA TODAS LAS COLUMNAS DE UNA TABLA:
-- TODOS LOS EMPLEADOS:
SELECT * FROM EMPLOYEES

-- CONSULTA CON EL NOMBRE DEL CLIENTE Y SU DIRECCION:
SELECT COMPANYNAME, ADDRESS FROM CUSTOMERS

-- CONSULTA CON CLAVE Y EL NOMBRE DEL EMPLEADO CON ENCCABEZADO
SELECT CLAVE = EMPLOYEEID, FIRSTNAME AS NOMBRE FROM EMPLOYEES

SELECT 'Clave del empleado' = employeeid, firstname as [Nombre del Empleado] from Employees

-- OPERADORES ARITMETICOS
-- CONCATENAR TEXTO A UN CAMPO DE TEXTO
SELECT 'El nombre es ' + firstname from Employees

-- Muestra el precio de los productos aumentando en 10, 20 y 30%
SELECT ProductName, 
'Original' = UnitPrice,
'10%'=UnitPrice * 1,1,
'20%'=UnitPrice * 1.2,
'30%'=UnitPrice * 1.3
FROM Products

-- IMPRIMIR EL AUMENTO SIMULADO DE 20 PESOS A TODOS LOS PRODUCTOS
SELECT PRODUCTNAME, UNITPRICE, 'AUMENTO EN 20 PESOS' = UNITPRICE+20 FROM PRODUCTS

-- TRES ELEVADO A LA CUARTA POTENCIA
SELECT ABS(-21)
SELECT FLOOR(3.9)
SELECT CEILING(3.1)
SELECT ROUND(12.23456, 2)
SELECT SIGN (12.3)
SELECT RAND()
SELECT POWER(3, 4)

-- ELEVAR AL CUADRADO EL PRECIO DE LOS PRODUCTOS
SELECT PRODUCTNAME, POWER(UNITPRICE, 2) FROM Products

-- IMPRIMIR LA RAIZ CUADRADA DEL PRECIO DE LOS PRODUCTOS
SELECT ProductName, UnitPrice, 'Raiz cuadrada'= sqrt(unitprice)
FROM Products

SELECT SUBSTRING('Culiacan, Sinaloa', 1,5)
SELECT RIGHT('Culiacan, Sinaloa', 7)

SELECT ASCII('A')
SELECT ASCII('a')

SELECT CHAR(65)

--MARCA ERROR
SELECT 'EL PRECIO ES' + 45.34

SELECT 'EL PRECIO ES' + LTrim(STR(45.34, 50, 2))

SELECT 'EL PRECIO ES' + CONVERT(CHAR(30), 45.34)

SELECT 'EL PRECIO ES'+ CAST( 45.34 AS CHAR(30))

SELECT 'ANA' + SPACE(100) + 'LARA'
SELECT DIFFERENCE('LARA', 'LARA')
SELECT DIFFERENCE('LARA', 'JORGE')
SELECT UPPER('LARA')
SELECT LOWER('CASTRO')

SELECT 'ANA' + LTrim('          casa')

-- MOSTRAR EL NOMBRE COMPLETO DE EMPLEADO
SELECT FIRSTNAME + CHAR(32) + ' ' + SPACE(1) + LASTNAME FROM EMPLOYEES

-- MOSTRAR EL NOMBRE DEL EMPLEADO COMO J. PEREZ
SELECT SUBSTRING (FIRSTNAME, 1,1) + '.' + SPACE(1) + LASTNAME FROM EMPLOYEES

-- MOSTRAR EN MAYUSCULAS EL NOMBRE COMPLETO DE EMPLEADO
SELECT UPPER(FIRSTNAME + ' ' + LASTNAME) FROM EMPLOYEES

-- MOSTRAR LA ULTIMA LETRA DEL APELLIDO DEL EMPLEADO
SELECT APELLIDO = LASTNAME,
ULTIMA = RIGHT(LASTNAME, 1),
ULTIMA = SUBSTRING(LASTNAME, LEN(LASTNAME),1)
FROM EMPLOYEES

-- DATEADD (DATEPART, NUMERO, FECHA)
-- DATEDIFF (DATEPART, FECHA1, FECHA2)
-- DATENAME (DATEPART, FECHA)
-- DATEPART
-- DAY, MONTH, YEAR 
-- GETDATE(), GETUTCDATE()

-- CONSULTA DE EMPLEADOS: Jose Lopez nacio el dia jueves 8 de enero de 1970
select firstname, lastname, birthdate from employees

select EMPLEADO =
firstname + ' ' + lastname + ' nacio el dia ' +
datename( dw,birthdate) + ' ' +
datename(dd, birthdate) + ' de ' +
datename(mm, birthdate) + ' de ' +
convert(char(4), datepart(yy, birthdate))
from employees

-- FUNCION QUE REGRESA LA FECHA DEL SERVIDOR
SELECT GETDATE()

-- CONSULTA CON LOS ANIOS VIVIDOS POR LOS EMPLEADOS(EDAD)
SELECT EMPLOYEEID, FIRSTNAME, BIRTHDATE,
DATEDIFF(YY, BIRTHDATE, GETDATE()),
YEAR(GETDATE())- YEAR(BIRTHDATE)
FROM EMPLOYEES

-- CONSULTA CON EL NOMBRE Y LA ANTIGUEDAD DE LOS EMPLEADOS 
SELECT FIRSTNAME, HIREDATE, ANTIGUEDAD = DATEDIFF(YY, HIREDATE,  GETDATE())
FROM EMPLOYEES

-- CONSULTA CON LA EDAD DEL EMPLEADO CUANDO ENTRO A TRABAJAR
SELECT FIRSTNAME, BIRTHDATE, HIREDATE, 'EDAD CUANDO ENTRO A TRABAJAR' = DATEDIFF(YY, BIRTHDATE, HIREDATE)
FROM EMPLOYEES

-- WHERE

-- CONSULTA CON LOS PRODUCTOS CON PRECIO MENOR A 30
SELECT*FROM PRODUCTS
WHERE UNITPRICE < 30

-- CONSULTA CON LOS EMPLEADOS QUE NACIERON ANTES DE 1960
SELECT*FROM EMPLOYEES
WHERE YEAR(BIRTHDATE) < 1960

-- OPERADOR BETWEEN
-- OPERADOR IN (VALORES QUE ESTAN DENTRO DE)

-- CONSULTA CON LOS PRODUCTOS CON PRECIO ENTRE 20 Y 50
SELECT*FROM PRODUCTS WHERE UNITPRICE BETWEEN 20 AND 50

-- CONSULTA CON LAS ORDENES DELPRIMER SEMESTRE DE 1998
SELECT *FROM ORDERS WHERE ORDERDATE BETWEEN '1-1-1998' AND '6-30-1998'

-- PRODUCTOS QUE VALGAN 10, 20 O 31
SELECT*FROM PRODUCTS WHERE UNITPRICE IN (10,20,31)

-- COMODINES PARA EL MANEJO DE CADENA DE CARACTERES:
-- % Una cadena con cero o mas caracteres ---------
-- _ Un solo caracter -----------------------------
-- [] Un caracter en un rango especifico ----------
---------------------------------------------------

-- CONSULTA CON LOS PRODUCTOS DONDE SU NOMBRE SEA IKURA
SELECT*FROM PRODUCTS WHERE PRODUCTNAME LIKE 'ikura'

-- CONSULTA CON LOS PRODUCTOS QUE EMPIECEN CON EL TEXTO "queso"
SELECT*FROM PRODUCTS WHERE PRODUCTNAME LIKE 'queso%'

-- CONSULTA CON LOS PRODUCTOS QUE TERMINEN CON LA CADENA "es"
SELECT*FROM PRODUCTS WHERE PRODUCTNAME LIKE '%es'

-- CONSULTA CON LOS PRODUCTOS QUE CONTENGAN LA CADENA "as"
SELECT*FROM PRODUCTS WHERE PRODUCTNAME LIKE '%as%'

-- CONSULTA CON LOS PRODUCTOS QUE EMPIECEN CON LA LETRA G Y TERMINEN CON LA LETRA A
SELECT*FROM PRODUCTS WHERE PRODUCTNAME LIKE'g%a'

-- CONSULTA CON LOS PRODUCTOS QUE EMPIECEN CON LA LETRA M,G,R
SELECT*FROM PRODUCTS 
WHERE PRODUCTNAME LIKE '[mgr]%'

SELECT*FROM PRODUCTS 
WHERE PRODUCTNAME LIKE 'm%' or PRODUCTNAME LIKE 'g%' OR PRODUCTNAME LIKE 'r%'

SELECT*FROM PRODUCTS 
WHERE SUBSTRING(PRODUCTNAME, 1, 1) IN ('m','g','r')

-- CONSULTA CON LOS PRODUCTOS QUE TERMINEN CON CONSONANTES
SELECT*FROM PRODUCTS WHERE PRODUCTNAME LIKE '%[^aeiou]'

SELECT*FROM PRODUCTS WHERE PRODUCTNAME NOT LIKE '%[aeiou]'

-- CONSULTA CON LOS PRODUCTOS QUE TENGAN 5 CARACTERES
SELECT*FROM PRODUCTS WHERE PRODUCTNAME LIKE '_____'
SELECT*FROM PRODUCTS WHERE LEN(PRODUCTNAME) = 5

-- CONSULTA CON LOS PRODUCTOS QUE EN LA TERCERA POSICION TENGAN UNA VOCAL
SELECT*FROM PRODUCTS WHERE PRODUCTNAME LIKE '__[aeiou]%'

-- CONSULTA CON LOS PRODUCTOS QUE SU PRIMERA PALABRA TENGA 5 CARACTERES
SELECT*FROM PRODUCTS WHERE PRODUCTNAME LIKE '_____ %'

-- VALORES DESCONOCIDOS 
-- IS [NOT] NULL ------
-----------------------
-- EMPLEADOS QUE NO TIENEN ASIGNADA UNA REGION
SELECT*FROM EMPLOYEES WHERE REGION IS NULL
-- ESTO ES UN ERROR:
SELECT*fROM EMPLOYEES WHERE REGION = NULL

-- CLIENTES QUE SI TIENEN ASIGNADO UN FAX
SELECT CUSTOMERID, COMPANYNAME, FAX FROM CUSTOMERS
WHERE FAX IS NOT NULL


-- ORDENAMIENTO --
-- ORDER BY ------
-- ASC \ DESC ----

-- CONSULTA CON LOS NOMBRES DE LOS EMPLEADOS ORDENADOS POR APELLIDO
SELECT EMPLOYEEID, LASTNAME, FIRSTNAME FROM EMPLOYEES 
ORDER BY LASTNAME ASC

-- PRODUCTOS ORDENADOS DE MAYOR A MENOR PRECIO
SELECT PRODUCTID, PRODUCTNAME, UNITPRICE FROM PRODUCTS
ORDER BY UNITPRICE DESC

SELECT PRODUCTID, PRODUCTNAME, UNITPRICE FROM PRODUCTS
ORDER BY 3 DESC

------------------
-- OPERADOR TOP --
------------------
-- CONSULTA CON LOS 5 PRODUCTOS MAS CAROS
SELECT TOP 5 PRODUCTID, PRODUCTNAME, UNITPRICE FROM PRODUCTS
ORDER BY UNITPRICE DESC

-- CONSULTA CON LOS 2 EMPLEADOS MAS JOVENES
SELECT TOP 2 EMPLOYEEID, FIRSTNAME, BIRTHDATE FROM EMPLOYEES
ORDER BY BIRTHDATE DESC

-- CONSULTA CON LAS 5 ORDENES DE 1996 DEL EMPLEADO 2
SELECT TOP 5 ORDERID, ORDERDATE, EMPLOYEEID
FROM ORDERS
WHERE EMPLOYEEID = 2 AND YEAR(ORDERDATE) = 1996
ORDER BY ORDERDATE DESC

-- CONSULTA CON LOS 2 PRODUCTOS MAS BARATOS DEL PROVEEDOR 2
SELECT TOP 2 PRODUCTID, PRODUCTNAME, UNITPRICE, SUPPLIERID
FROM PRODUCTS
WHERE SUPPLIERID = 2
ORDER BY UNITPRICE ASC

-- CORRELACION DE DATOS
-- EXISTEN DISTINTAS COMBINACIONES (JOIN):
-- CRUZADAS (CROSS JOIN)
-- INTERNAS (INNER JOIN)
-- EXTERNAS (OUTER JOIN)
-- AUTOCOMBINACIONES (SELF JOIN)


-- CROSS JOIN
-- 10 COLLUMNAS, 77 RENGONLES
SELECT * FROM PRODUCTS

-- 4 COLUMNAS, 8 RENGLONES
SELECT * FROM CATEGORIES

SELECT*FROM PRODUCTS CROSS JOIN CATEGORIES
SELECT*FROM PRODUCTS, CATEGORIES

-- COLUMNAS: 10 + 4 = 14
-- RENGLONES 77*8 = 616

-- COLUMNAS 12, RENGLONES 29
SELECT * FROM SUPPLIERS

SELECT*FROM PRODUCTS CROSS JOIN CATEGORIES CROSS JOIN SUPPLIERS
-- COLUMNAS: 10 + 4 + 12 = 26
-- RENGLONES: 77*8*29 = 17,864

-- INNER JOIN
-- SELECT*
-- FROM TABLE_NAME1 T1 
-- INNER JOIN TABLE_NAME2 T2
-- ON T1.COLUMNAA = T2.COLUMNAB

-- CONULTA CON EL NOMBRE DEL PRODUCTO Y EL NOMBRE DE SU CATEGORIA
SELECT PRODUCTS.ProductName, CATEGORIES.CategoryName
FROM PRODUCTS
INNER JOIN CATEGORIES 
ON CATEGORIES.CategoryID = PRODUCTS.CategoryID

SELECT P.PRODUCTNAME, C.CATEGORYNAME
FROM PRODUCTS P
INNER JOIN CATEGORIES C ON C.CategoryID = P.CategoryID

-- CON TRANSACT-SQL
SELECT P.PRODUCTNAME, C.CATEGORYNAME
FROM PRODUCTS P, CATEGORIES C
WHERE C.CategoryID = P.CategoryID

-- CONSULTA CON UN LOS PRODUCTOS CON UN PRECIO MENORES A 20 PESOS,
-- MOSTRAR EL NOMBRE DEL PRODUCTO, PRECIO, NOMBRE DE LA CATEGORIA
SELECT P.ProductName, P.UnitPrice, P.CategoryID, C.CategoryID, C.CategoryName
FROM PRODUCTS P 
INNER JOIN CATEGORIES C ON C.CategoryID = P.CategoryID
WHERE P.UNITPRICE < 20

-- CONSULTA CON LA CLAVE Y FECHA DE LA ORDEN, NOMBRE DEL EMPLEADO Y
-- NOMBRE DEL CLIENTE, MOSTRAR SOLO LAS ORDENES REALIZADAS EN 1996
SELECT ORDERID, ORDERDATE, EMPLEADO = E.FIRSTNAME + ' ' + E.LASTNAME, C.COMPANYNAME
FROM ORDERS O
INNER JOIN Employees E ON E.EMPLOYEEID = O.EMPLOYEEID 
INNER JOIN CUSTOMERS C ON C.CustomerID = O.CustomerID
WHERE
YEAR(O.ORDERDATE)=1996

-- CONSULTA CON LA CLAVE DE LA ORDEN, NOMBRE DEL PRODUCTO, CANTIDAD, PRECIO Y
-- TOTAL DE LA VENTA
-- MOSTRAR SOLO LAS ORDENES REALOZADAS LOS DIAS LUNES
SELECT O.OrderID, [DIA DE LA SEMANA] = DATENAME(DW, O.ORDERDATE), P.ProductName, D.Quantity, D.UnitPrice, 
TOTAL = D.Quantity * D.UnitPrice
FROM ORDERS O
INNER JOIN [ORDER DETAILS] D ON D.OrderID = O.OrderID
INNER JOIN PRODUCTS P ON P.ProductID = D.PRODUCTID
WHERE
DATEPART(DW, O.ORDERDATE) = 2

-- CONSULTA CON EL NOMBRE DEL EMPLEADO Y NOMBRE DEL TERRITORIO QUE ATIENDE
SELECT NOMBRE = E.FIRSTNAME + ' ' + E.LASTNAME, TERRITORIO = T.TERRITORYDESCRIPTION
FROM EMPLOYEES E
INNER JOIN EMPLOYEETERRITORIES X ON X.EMPLOYEEID = E.EMPLOYEEID
INNER JOIN TERRITORIES T ON T.TERRITORYID = X.TerritoryID
-- LA TABLA EMPLOYEETERRITORIES ES LA TABLA PRINCIPAL --

-- CONSULTA CON EL NOMBRE DEL EMPLEADO Y NOMBRE DE SU JEFE
SELECT
CLAVEEMP = E.EmployeeID, EMPLEADO = E.FirstName + ' ' + E.LastName,
CLAVEJEFE = J.EMPLOYEEID, JEFE = J.FirstName + ' ' + J.LastName
FROM EMPLOYEES E
INNER JOIN EMPLOYEES J ON E.ReportsTo = J.EmployeeID

SELECT EMPLOYEEID, REPORTSTO FROM EMPLOYEES

-- MEIDANTE UNA CONMBINACION  EXTERNA, SE PUEDE MOSTRAR TODOS LOS EMPLEADOS AUNQUE
-- NO TENGA JEFE
-- IZQUIERDA
SELECT 
CLAVEEMP = E.EMPLOYEEID, EMPLEADO =  E.FIRSTNAME + ' ' + E.LASTNAME,
CLAVEJEFE = E.REPORTSTO, JEFE = J.FIRSTNAME + ' ' + J.LASTNAME
FROM EMPLOYEES E LEFT OUTER JOIN EMPLOYEES J ON E.ReportsTo = J.EmployeeID
-- DERECHA
SELECT 
CLAVEEMP = E.EMPLOYEEID, EMPLEADO =  E.FIRSTNAME + ' ' + E.LASTNAME,
CLAVEJEFE = E.REPORTSTO, JEFE = J.FIRSTNAME + ' ' + J.LASTNAME
FROM EMPLOYEES J RIGHT OUTER JOIN EMPLOYEES E ON E.ReportsTo = J.EMPLOYEEID 












































